import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import seoRouter from "./seo";
import customizationsRouter from "./customizations";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import usersRouter from "./users";
import adminRouter from "./admin";
import adminExtraRouter from "./adminExtra";
import paymentsRouter from "./payments";
import siteSettingsRouter from "./siteSettings";
import r2proxyRouter from "./r2proxy";
import skuAssetsRouter from "./skuAssets";
import contactRouter from "./contact";
import lookbookRouter from "./lookbook";
import clubOrdersRouter from "./club-orders";
import shiprocketWebhookRouter from "./shiprocketWebhook";
import couponsRouter from "./coupons";
import creditsRouter from "./credits";
import adminCreditsRouter from "./adminCredits";
import razorpayWebhookRouter from "./razorpayWebhook";

const router: IRouter = Router();

router.use(shiprocketWebhookRouter);
router.use(razorpayWebhookRouter);
router.use(healthRouter);
router.use(productsRouter);
router.use("/seo", seoRouter);
router.use(customizationsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(adminExtraRouter);
router.use(paymentsRouter);
router.use(siteSettingsRouter);
router.use(r2proxyRouter);
router.use(skuAssetsRouter);
router.use(contactRouter);
router.use(lookbookRouter);
router.use(clubOrdersRouter);
router.use(couponsRouter);
router.use(creditsRouter);
router.use(adminCreditsRouter);

export default router;
